// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Transaction struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Amount    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID       uuid.UUID
	Name     string
	Email    string
	Password string
	Token    string
}
