// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Transaction struct {
	ID        int32
	UserID    int32
	Amount    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID       int32
	Name     string
	Email    string
	Password string
	Token    sql.NullString
}
